### PR TITLE
Fixing decode of “+"

### PR DESCRIPTION
**Pull request by Pearapps**
These should be converted to spaces on decode

### CODE REVIEW

**Comment by brianmichel** [comment]
Is it worth breaking these lines out for clarity? Also Is there an easy way for me to verify what this change does?

**Comment by brianmichel** [comment]
Also, why should they be converted? What’s the motivation here?

**Comment by Pearapps** [comment]
> Is it worth breaking these lines out for clarity?

I don’t think so.

**Comment by Pearapps** [comment]
> Also, why should they be converted? What’s the motivation here?

On decode, `+`s should be converted to spaces. 

@ceyko

**Comment by ceyko** [comment]
@brianmichel This is to fulfill [RFC-5849 § 3.4.1.3.1](http://tools.ietf.org/html/rfc5849#section-3.4.1.3.1), which states that when gathering parameters for computing the base string of the signature, you _must_ decode `+` to ` `.

This function is used in computing the base string, but I can't say for sure that _everywhere_ it is used this is acceptable. For instance, `+` in `multipart/form-data` does not actually represent a space - only `application/x-www-form-urlencoded` data.

However, our signature logic is already off-spec for `multipart/form-data` though, as RFC-5849 says that the body should not be included in the signature, but we do it anyway. So, I'm not too worried about this from an signature perspective, just other usages.

**Pull request merged**
